### ISSUE TITLE
The spectrum update time is very laggy

### ISSUE THREAD

**Issue by pashashocky** [lucy/mpdviz#1]
I dont know why I am getting this, maybe its just me being stupid, but as the video shows the spectrum update time is much laggier than the wave and lines: 

http://quick.as/gbgfn9o

**Comment by lucy** [comment]
What are your specs? What terminal emulator are you using?

**Comment by pashashocky** [comment]
Mbpr 13" late 2012, with i5, running terminal.app

**Comment by spaghetti-** [comment]
try iterm2
