### ISSUE TITLE
howto compile on debian...

### ISSUE THREAD

**Issue by dru8274** [lucy/mpdviz#3]
I am on Debian testing (nee Crunchbang), but quite keen to compile and run mpdviz. Following the commands in aur/PKGBUILD, it has worked okay up until the "go install" command. With this error

  # github.com/neeee/mpdviz
cannot create nil/go.o: No such file or directory

I'm not expert on compiling for Go. Or how arch makepkg runs a specific PKGBUILD script. Can you see howto fix this error plz?

---

user: $ apt-get install  golang cl-fftw3     # install Go language and fftw3
user: $ cd temp
user: $ pkgname=mpdviz
user: $ pkgver=0.4.2
user: $ pkgrel=1
user: $ pkgdesc='Standalone console MPD visualizer'
user: $ export  arch=('x86_64' 'i686' )
user: $ export  url='https://github.com/neeee/mpdviz'
user: $ license=('MIT')
user: $ makedepends=('go')
user: $ depends=('fftw')
user: $ export options=('!emptydirs')
user: $ export  _gourl='github.com/neeee/mpdviz'
user: $ export srcdir="$PWD"
user: $ export PKG_CONFIG_PATH=/usr/lib/pkgconfig
user: $ export GOPATH="$srcdir"
user: $ export PATH=$PATH:$GOPATH/bin
user: $
user: $ go get -u -d -v "$_gourl"
github.com/neeee/mpdviz (download)
github.com/neeee/go-fftw (download)
github.com/neeee/pflag (download)
github.com/neeee/termbox-go (download)
user: $ 
user: $ cd "$srcdir/src/$_gourl"
user: $ git checkout -q tags/$pkgver
user: $ 
user: $ go install
 # github.com/neeee/mpdviz
cannot create nil/go.o: No such file or directory

**Comment by vendion** [comment]
If you have Go installed and setup (check `go version` and `echo $GOPATH` and `echo $GOBIN`) then all you have to do is `go get github.com/lucy/mpdviz` that will download, build and install the binary in where you have $GOBIN set.
